# Generated by Django 2.2.19 on 2021-12-05 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('rented', models.BooleanField()),
                ('rentprice', models.CharField(db_column='rentPrice', max_length=10)),
                ('bedrooms', models.CharField(max_length=5)),
                ('bathrooms', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Propertymanagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'main_propertymanagement',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('jointtenantname', models.CharField(blank=True, db_column='jointTenantName', max_length=100)),
                ('pets', models.BooleanField(blank=True)),
                ('paidrent', models.BooleanField(blank=True, db_column='paidRent')),
                ('leaseexpdate', models.CharField(db_column='leaseExpDate', max_length=100)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=14)),
                ('email', models.CharField(max_length=40)),
                ('lease', models.CharField(blank=True, max_length=12000)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_tenant',
            },
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'main_urgency',
            },
        ),
        migrations.CreateModel(
            name='Troubleticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=500)),
                ('datereceived', models.CharField(blank=True, db_column='dateReceived', max_length=25)),
                ('datecompleted', models.CharField(db_column='dateCompleted', max_length=25)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tenant')),
            ],
            options={
                'db_table': 'main_troubleticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketno', models.IntegerField(blank=True, default='911')),
                ('date', models.CharField(db_column='Date', max_length=17)),
                ('issue', models.CharField(max_length=500)),
                ('complete', models.BooleanField(blank=True, db_column='Complete')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('dateComplete', models.CharField(blank=True, max_length=17)),
                ('category', models.ForeignKey(db_column='Category_id', on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('item', models.ForeignKey(db_column='Item_id', on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('tenant', models.ForeignKey(db_column='Tenant_id', on_delete=django.db.models.deletion.CASCADE, to='main.Tenant')),
                ('urgency', models.ForeignKey(db_column='Urgency_id', on_delete=django.db.models.deletion.CASCADE, to='main.Urgency')),
            ],
            options={
                'db_table': 'main_ticket',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='propertymanagement',
            field=models.ForeignKey(db_column='PropertyManagement_id', default=5, on_delete=django.db.models.deletion.CASCADE, to='main.Propertymanagement'),
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(db_column='Tenant_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='main.Tenant'),
        ),
    ]
