# Generated by Django 2.2.19 on 2021-12-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateComplete',
            field=models.CharField(blank=True, default='Jan 01, 1970', max_length=17),
        ),
    ]
