# Generated by Django 2.2.19 on 2021-12-05 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211204_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(db_column='Category_id', on_delete=django.db.models.deletion.PROTECT, to='main.Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='item',
            field=models.ForeignKey(db_column='Item_id', on_delete=django.db.models.deletion.PROTECT, to='main.Item'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tenant',
            field=models.ForeignKey(db_column='Tenant_id', on_delete=django.db.models.deletion.PROTECT, to='main.Tenant'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.ForeignKey(db_column='Urgency_id', on_delete=django.db.models.deletion.PROTECT, to='main.Urgency'),
        ),
    ]
