# Generated by Django 2.2.19 on 2021-12-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211204_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, db_column='Category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='item',
            field=models.ForeignKey(blank=True, db_column='Item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Item'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='Tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Tenant'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.ForeignKey(blank=True, db_column='Urgency_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Urgency'),
        ),
    ]
